language: cpp
sudo: required
dist: bionic

env:
  global:
  # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
  #   via the "travis encrypt" command using the project repo's public key
  - secure: UgoWZDJPOrFmjDxW+RwUkGU5tPZJwA7K2is7fm7OPkVRfu6qLSit+tIGV2JEkOvubwT/JxsEPOg3ViV6oVFKIgl7svE5NoWDAfVeo7LN1537sVvfP79LfqcfFdiGubj4Lu1uudIK5upFC7IHRrcDcJJWztdqr+8mmJXx7Nr4qjBYqxgAIjq1ibrJpDxDLV+Hukl2GExxwEYccoEXmaKsjpQ3mAds8Jt2D8TnsuUmbGbokwyZcGZGgYoqFLyKlSbfixxoy84KZY5zOeRS6tyaQeXg0bn61lXLaeSECx4zDd0qFPNJPdlMnLphRy2F7HpQls0R4sNCd4/bjCQd0c4LLyagqmfnp09rdFb+TnrLGa8VBfBbOKJVerp98oUXUdx8ZI9iIZGQJwabvhdjhzlHN8fGeqIuI2sKNpE9grw2FGlzUA3t8ynL5jGsBNILd8S9/TNzcewrRRUKTZdCIZm3wSIHTSj9B+6Fq4Y/1wNJ4KjIWEk5WxAaD4YUgqvHsW2in948WvRRuncNQlj7Y8NQwRqzTROTz7X1V1WkRUYzo69g4HOUopvl4VbcgOk2IXB7YzOeSRiFJ4SRCQO6xC/2eX10x2vVI7UMEIelmr06a73wBdcR8cqRL1/rw51qoKQWwyoxoZdypfAMm/i9zZHWe2F8nJ8tzuAF/MkwMxbh9qE=
  - ASAN_OPTIONS='halt_on_error=1'
  - UBSAN_OPTIONS='halt_on_error=1'

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  apt:
    packages:
    - gcc g++ binutils
  # Coverity scan add-on, fires only when pushing to the `coverity_scan` branch
  coverity_scan:
    project:
      name: "ugtrain"
      description: "Build submitted via Travis CI"
    notification_email: s.parschauer@gmx.de
    build_command_prepend: "./autogen.sh && ./configure"
    build_command: "make"
    branch_pattern: coverity_scan

script:
  - if [ "${COVERITY_SCAN_BRANCH}" == 1 ]; then exit ; fi
  - ./autogen.sh && ./configure
  - make CFLAGS='-O2 -fsanitize=address,undefined'
